package demo.users.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Address implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Street")
   private String street;
   @org.kie.api.definition.type.Label("Number")
   private Integer number;
   @org.kie.api.definition.type.Label("CP")
   private String cp;
   @org.kie.api.definition.type.Label("City")
   private String city;

   public Address()
   {
   }

   public String getStreet()
   {
      return this.street;
   }

   public void setStreet(String street)
   {
      this.street = street;
   }

   public Integer getNumber()
   {
      return this.number;
   }

   public void setNumber(Integer number)
   {
      this.number = number;
   }

   public String getCp()
   {
      return this.cp;
   }

   public void setCp(String cp)
   {
      this.cp = cp;
   }

   public String getCity()
   {
      return this.city;
   }

   public void setCity(String city)
   {
      this.city = city;
   }

   public Address(String street, Integer number,
         String cp, String city)
   {
      this.street = street;
      this.number = number;
      this.cp = cp;
      this.city = city;
   }

}