package demo.users.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Company implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Name")
   private String name;
   @org.kie.api.definition.type.Label("Identifier")
   private String id;
   @org.kie.api.definition.type.Label("Employees number")
   private Integer employees;

   public Company()
   {
   }

   public String getName()
   {
      return this.name;
   }

   public void setName(String name)
   {
      this.name = name;
   }

   public String getId()
   {
      return this.id;
   }

   public void setId(String id)
   {
      this.id = id;
   }

   public Integer getEmployees()
   {
      return this.employees;
   }

   public void setEmployees(Integer employees)
   {
      this.employees = employees;
   }

   public Company(String name, String id,
         Integer employees)
   {
      this.name = name;
      this.id = id;
      this.employees = employees;
   }

   public Company(String id, String name)
   {
      this.id = id;
      this.name = name;
   }

}