package demo.users.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class User implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("User Name")
   private String name;
   @org.kie.api.definition.type.Label("User Last Name")
   private String lastName;
   @org.kie.api.definition.type.Label("Birthday")
   private java.util.Date birthday;
   @org.kie.api.definition.type.Label("Married")
   private Boolean married;

   @org.kie.api.definition.type.Label(value = "Identifier")
   private String id;

   public User()
   {
   }

   public String getName()
   {
      return this.name;
   }

   public void setName(String name)
   {
      this.name = name;
   }

   public String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(String lastName)
   {
      this.lastName = lastName;
   }

   public java.util.Date getBirthday()
   {
      return this.birthday;
   }

   public void setBirthday(java.util.Date birthday)
   {
      this.birthday = birthday;
   }

   public Boolean getMarried()
   {
      return this.married;
   }

   public void setMarried(Boolean married)
   {
      this.married = married;
   }

   public String getId()
   {
      return this.id;
   }

   public void setId(String id)
   {
      this.id = id;
   }

   public User(String name, String lastName,
         java.util.Date birthday, Boolean married, String id)
   {
      this.name = name;
      this.lastName = lastName;
      this.birthday = birthday;
      this.married = married;
      this.id = id;
   }

}